### ISSUE TITLE
Final Upload Checklist

### ISSUE THREAD

**Issue by Amber21457752** [COS214-Project-2024/WorksOnMyMachineTeam#66]
- [x] System Files: All source files (.h and .cpp) and your Makefile.
- [x] Data Files: Any necessary data files required to run the program.
- [x] Readme: A readme.md in the root directory containing a short description of your project, explaining how to compile and run the program, and the placement of any data files.
- [x] Report: A PDF version of your latest report in a folder named Report. The report must also be written in Google Docs, with a link to the Google Docs version included in the PDF.
- [x] System Folder: Place all system files in a folder named System. Running your Makefile in this folder should compile and link your system correctly.
- [x] Data Folder: Place your data files, if any, in a folder named Data.
